package pohaci.gumunda.titis.accounting.cgui;

/**
 * <p>Title: Project Management</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * <p>Company: </p>
 * @author dewax4
 * @version 1.0
 */

public class BankLoanPaymentPanel extends javax.swing.JPanel {

  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
/** Creates new form Panel1 */
  public BankLoanPaymentPanel() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jPanel1_1 = new javax.swing.JPanel();
    jPanel1_1_1 = new javax.swing.JPanel();
    jToggleButton1 = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    m_NewBtn = new javax.swing.JButton();
    m_EditBtn = new javax.swing.JButton();
    m_DeleteBtn = new javax.swing.JButton();
    m_SaveBtn = new javax.swing.JButton();
    m_CancelBtn = new javax.swing.JButton();
    m_SubmitBtn = new javax.swing.JButton();
    jPanel1_2 = new javax.swing.JPanel();
    jPanel1_2_2 = new javax.swing.JPanel();
    jPanel1_2_2_1 = new javax.swing.JPanel();
    VoucherNoLabel = new javax.swing.JLabel();
    VoucherNoText = new javax.swing.JTextField();
    VoucherDateLabel = new javax.swing.JLabel();
    VoucherDateText = new javax.swing.JTextField();
    DescriptionLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    RemarksLabel = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jPanel1_2_1 = new javax.swing.JPanel();
    StatusLabel = new javax.swing.JLabel();
    SubmittedDateLabel = new javax.swing.JLabel();
    PaymentSourceLabel = new javax.swing.JLabel();
    AccountLabel = new javax.swing.JLabel();
    StatusText = new javax.swing.JTextField();
    SubmittedDateText = new javax.swing.JTextField();
    PaymentSourceCombo = new javax.swing.JComboBox();
    AccountText = new javax.swing.JTextField();
    ChequeNoLabel = new javax.swing.JLabel();
    ChequeDueDateLabel = new javax.swing.JLabel();
    ChequeNoText = new javax.swing.JTextField();
    PayToLabel = new javax.swing.JLabel();
    AccountLabel2 = new javax.swing.JLabel();
    ChequeDueDateText = new javax.swing.JTextField();
    InitialLoanLabel = new javax.swing.JLabel();
    PayToText = new javax.swing.JTextField();
    AccountText2 = new javax.swing.JTextField();
    InitialLoanText = new javax.swing.JTextField();
    UnitCodeToLabel = new javax.swing.JLabel();
    UnitCodeToText = new javax.swing.JTextField();
    jPanel1_2_1_1 = new javax.swing.JPanel();
    CurrencyLabel = new javax.swing.JLabel();
    CurrencyText = new javax.swing.JTextField();
    ExchRateLabel = new javax.swing.JLabel();
    ExchRateText = new javax.swing.JTextField();
    AmountLabel = new javax.swing.JLabel();
    AmountText = new javax.swing.JTextField();
    AmountBaseCurrLabel = new javax.swing.JLabel();
    AmountBaseCurrentText = new javax.swing.JTextField();
    EndingBalanceLabel = new javax.swing.JLabel();
    EndingBalanceText = new javax.swing.JTextField();
    jPanel1_3 = new javax.swing.JPanel();
    jPanel1_3_1 = new javax.swing.JPanel();
    EmployeeOriLabel = new javax.swing.JLabel();
    JobTitleOriLabel = new javax.swing.JLabel();
    DateOriLabel = new javax.swing.JLabel();
    EmployeeOriText = new javax.swing.JTextField();
    JobTitleOriText = new javax.swing.JTextField();
    DateOriText = new javax.swing.JTextField();
    jPanel1_3_2 = new javax.swing.JPanel();
    jPanel1_3_2_1 = new javax.swing.JPanel();
    EmployeeAppLabel = new javax.swing.JLabel();
    EmployeeAppText = new javax.swing.JTextField();
    JobTitleAppText = new javax.swing.JTextField();
    DateAppText = new javax.swing.JTextField();
    JobTitleAppLabel = new javax.swing.JLabel();
    DateAppLabel = new javax.swing.JLabel();
    jPanel1_3_2_2 = new javax.swing.JPanel();
    jPanel1_3_2_2_1 = new javax.swing.JPanel();
    EmployeeRcvLabel = new javax.swing.JLabel();
    EmployeeRcvText = new javax.swing.JTextField();
    JobTitleRcvText = new javax.swing.JTextField();
    DateRcvText = new javax.swing.JTextField();
    JobTitleRcvLabel = new javax.swing.JLabel();
    DateRcvLabel = new javax.swing.JLabel();

    setLayout(new java.awt.BorderLayout());

    setPreferredSize(new java.awt.Dimension(700, 550));
    jPanel1.setLayout(new java.awt.BorderLayout());

    jPanel1.setPreferredSize(new java.awt.Dimension(670, 525));
    jPanel1_1.setLayout(new java.awt.BorderLayout());

    jPanel1_1.setPreferredSize(new java.awt.Dimension(700, 35));
    jPanel1_1_1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 5));

    jPanel1_1_1.setPreferredSize(new java.awt.Dimension(650, 35));
    jToggleButton1.setPreferredSize(new java.awt.Dimension(21, 21));
    jPanel1_1_1.add(jToggleButton1);

    jToggleButton2.setPreferredSize(new java.awt.Dimension(21, 21));
    jPanel1_1_1.add(jToggleButton2);

    m_NewBtn.setText("New");
    m_NewBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
    m_NewBtn.setPreferredSize(new java.awt.Dimension(50, 21));
    jPanel1_1_1.add(m_NewBtn);

    m_EditBtn.setText("Edit");
    m_EditBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
    m_EditBtn.setPreferredSize(new java.awt.Dimension(50, 21));
    jPanel1_1_1.add(m_EditBtn);

    m_DeleteBtn.setText("Delete");
    m_DeleteBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
    m_DeleteBtn.setPreferredSize(new java.awt.Dimension(50, 21));
    jPanel1_1_1.add(m_DeleteBtn);

    m_SaveBtn.setText("Save");
    m_SaveBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
    m_SaveBtn.setPreferredSize(new java.awt.Dimension(50, 21));
    jPanel1_1_1.add(m_SaveBtn);

    m_CancelBtn.setText("Cancel");
    m_CancelBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
    m_CancelBtn.setPreferredSize(new java.awt.Dimension(50, 21));
    jPanel1_1_1.add(m_CancelBtn);

    m_SubmitBtn.setText("Submit");
    m_SubmitBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
    m_SubmitBtn.setPreferredSize(new java.awt.Dimension(50, 21));
    jPanel1_1_1.add(m_SubmitBtn);

    jPanel1_1.add(jPanel1_1_1, java.awt.BorderLayout.WEST);

    jPanel1.add(jPanel1_1, java.awt.BorderLayout.NORTH);

    jPanel1_2.setLayout(new java.awt.BorderLayout());

    jPanel1_2.setPreferredSize(new java.awt.Dimension(700, 300));
    jPanel1_2_2.setLayout(new java.awt.BorderLayout());

    jPanel1_2_2.setPreferredSize(new java.awt.Dimension(325, 400));
    jPanel1_2_2_1.setLayout(new java.awt.GridBagLayout());

    jPanel1_2_2_1.setPreferredSize(new java.awt.Dimension(325, 325));
    VoucherNoLabel.setText("Voucher No*");
    VoucherNoLabel.setPreferredSize(new java.awt.Dimension(100, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(VoucherNoLabel, gridBagConstraints);

    VoucherNoText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(VoucherNoText, gridBagConstraints);

    VoucherDateLabel.setText("Voucher Date*");
    VoucherDateLabel.setPreferredSize(new java.awt.Dimension(100, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(VoucherDateLabel, gridBagConstraints);

    VoucherDateText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(VoucherDateText, gridBagConstraints);

    DescriptionLabel.setText("Description*");
    DescriptionLabel.setPreferredSize(new java.awt.Dimension(85, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(DescriptionLabel, gridBagConstraints);

    jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 150));
    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(jScrollPane1, gridBagConstraints);

    RemarksLabel.setText("Remarks");
    RemarksLabel.setPreferredSize(new java.awt.Dimension(85, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(RemarksLabel, gridBagConstraints);

    jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 150));
    jTextArea2.setColumns(20);
    jTextArea2.setLineWrap(true);
    jTextArea2.setRows(5);
    jScrollPane2.setViewportView(jTextArea2);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
    jPanel1_2_2_1.add(jScrollPane2, gridBagConstraints);

    jPanel1_2_2.add(jPanel1_2_2_1, java.awt.BorderLayout.WEST);

    jPanel1_2.add(jPanel1_2_2, java.awt.BorderLayout.CENTER);

    jPanel1_2_1.setLayout(new java.awt.GridBagLayout());

    jPanel1_2_1.setPreferredSize(new java.awt.Dimension(330, 325));
    StatusLabel.setText("Status");
    StatusLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(StatusLabel, gridBagConstraints);

    SubmittedDateLabel.setText("Submitted Date");
    SubmittedDateLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(SubmittedDateLabel, gridBagConstraints);

    PaymentSourceLabel.setText("Payment Source*");
    PaymentSourceLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(PaymentSourceLabel, gridBagConstraints);

    AccountLabel.setText("Account*");
    AccountLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(AccountLabel, gridBagConstraints);

    StatusText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(StatusText, gridBagConstraints);

    SubmittedDateText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(SubmittedDateText, gridBagConstraints);

    PaymentSourceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    PaymentSourceCombo.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(PaymentSourceCombo, gridBagConstraints);

    AccountText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(AccountText, gridBagConstraints);

    ChequeNoLabel.setText("Cheque No");
    ChequeNoLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(ChequeNoLabel, gridBagConstraints);

    ChequeDueDateLabel.setText("Cheque Due Date");
    ChequeDueDateLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(ChequeDueDateLabel, gridBagConstraints);

    ChequeNoText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(ChequeNoText, gridBagConstraints);

    PayToLabel.setText("Pay To*");
    PayToLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(PayToLabel, gridBagConstraints);

    AccountLabel2.setText("Account");
    AccountLabel2.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(AccountLabel2, gridBagConstraints);

    ChequeDueDateText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(ChequeDueDateText, gridBagConstraints);

    InitialLoanLabel.setText("Initial Loan");
    InitialLoanLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(InitialLoanLabel, gridBagConstraints);

    PayToText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(PayToText, gridBagConstraints);

    AccountText2.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(AccountText2, gridBagConstraints);

    InitialLoanText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(InitialLoanText, gridBagConstraints);

    UnitCodeToLabel.setText("Current Balance");
    UnitCodeToLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(UnitCodeToLabel, gridBagConstraints);

    UnitCodeToText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(UnitCodeToText, gridBagConstraints);

    jPanel1_2_1_1.setLayout(new java.awt.GridBagLayout());

    jPanel1_2_1_1.setPreferredSize(new java.awt.Dimension(320, 75));
    CurrencyLabel.setText("Currency*");
    CurrencyLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 1);
    jPanel1_2_1_1.add(CurrencyLabel, gridBagConstraints);

    CurrencyText.setPreferredSize(new java.awt.Dimension(30, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 1, 3, 3);
    jPanel1_2_1_1.add(CurrencyText, gridBagConstraints);

    ExchRateLabel.setText("Exch. Rate");
    ExchRateLabel.setPreferredSize(new java.awt.Dimension(60, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 3);
    jPanel1_2_1_1.add(ExchRateLabel, gridBagConstraints);

    ExchRateText.setPreferredSize(new java.awt.Dimension(100, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 1, 3, 3);
    jPanel1_2_1_1.add(ExchRateText, gridBagConstraints);

    AmountLabel.setText("Amount");
    AmountLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1_1.add(AmountLabel, gridBagConstraints);

    AmountText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1_1.add(AmountText, gridBagConstraints);

    AmountBaseCurrLabel.setText("Amount Base Curr.");
    AmountBaseCurrLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 1);
    jPanel1_2_1_1.add(AmountBaseCurrLabel, gridBagConstraints);

    AmountBaseCurrentText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 0, 3);
    jPanel1_2_1_1.add(AmountBaseCurrentText, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel1_2_1.add(jPanel1_2_1_1, gridBagConstraints);

    EndingBalanceLabel.setText("Ending Balance");
    EndingBalanceLabel.setPreferredSize(new java.awt.Dimension(110, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_2_1.add(EndingBalanceLabel, gridBagConstraints);

    EndingBalanceText.setPreferredSize(new java.awt.Dimension(200, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 3);
    jPanel1_2_1.add(EndingBalanceText, gridBagConstraints);

    jPanel1_2.add(jPanel1_2_1, java.awt.BorderLayout.WEST);

    jPanel1.add(jPanel1_2, java.awt.BorderLayout.CENTER);

    jPanel1_3.setLayout(new java.awt.BorderLayout());

    jPanel1_3.setPreferredSize(new java.awt.Dimension(700, 110));
    jPanel1_3_1.setLayout(new java.awt.GridBagLayout());

    jPanel1_3_1.setBorder(javax.swing.BorderFactory.createTitledBorder("Originator"));
    jPanel1_3_1.setOpaque(false);
    jPanel1_3_1.setPreferredSize(new java.awt.Dimension(215, 110));
    EmployeeOriLabel.setText("Employee");
    EmployeeOriLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_1.add(EmployeeOriLabel, gridBagConstraints);

    JobTitleOriLabel.setText("Job Title");
    JobTitleOriLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_1.add(JobTitleOriLabel, gridBagConstraints);

    DateOriLabel.setText("Date");
    DateOriLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_1.add(DateOriLabel, gridBagConstraints);

    EmployeeOriText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_1.add(EmployeeOriText, gridBagConstraints);

    JobTitleOriText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_1.add(JobTitleOriText, gridBagConstraints);

    DateOriText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_1.add(DateOriText, gridBagConstraints);

    jPanel1_3.add(jPanel1_3_1, java.awt.BorderLayout.WEST);

    jPanel1_3_2.setLayout(new java.awt.BorderLayout());

    jPanel1_3_2.setPreferredSize(new java.awt.Dimension(430, 110));
    jPanel1_3_2_1.setLayout(new java.awt.GridBagLayout());

    jPanel1_3_2_1.setBorder(javax.swing.BorderFactory.createTitledBorder("Approved by"));
    jPanel1_3_2_1.setOpaque(false);
    jPanel1_3_2_1.setPreferredSize(new java.awt.Dimension(215, 110));
    EmployeeAppLabel.setText("Employee");
    EmployeeAppLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_2_1.add(EmployeeAppLabel, gridBagConstraints);

    EmployeeAppText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_2_1.add(EmployeeAppText, gridBagConstraints);

    JobTitleAppText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_2_1.add(JobTitleAppText, gridBagConstraints);

    DateAppText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_2_1.add(DateAppText, gridBagConstraints);

    JobTitleAppLabel.setText("Job Title");
    JobTitleAppLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_2_1.add(JobTitleAppLabel, gridBagConstraints);

    DateAppLabel.setText("Date");
    DateAppLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_2_1.add(DateAppLabel, gridBagConstraints);

    jPanel1_3_2.add(jPanel1_3_2_1, java.awt.BorderLayout.WEST);

    jPanel1_3_2_2.setLayout(new java.awt.BorderLayout());

    jPanel1_3_2_2.setPreferredSize(new java.awt.Dimension(215, 110));
    jPanel1_3_2_2_1.setLayout(new java.awt.GridBagLayout());

    jPanel1_3_2_2_1.setBorder(javax.swing.BorderFactory.createTitledBorder("Received by"));
    jPanel1_3_2_2_1.setOpaque(false);
    jPanel1_3_2_2_1.setPreferredSize(new java.awt.Dimension(215, 110));
    EmployeeRcvLabel.setText("Employee");
    EmployeeRcvLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_2_2_1.add(EmployeeRcvLabel, gridBagConstraints);

    EmployeeRcvText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_2_2_1.add(EmployeeRcvText, gridBagConstraints);

    JobTitleRcvText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_2_2_1.add(JobTitleRcvText, gridBagConstraints);

    DateRcvText.setPreferredSize(new java.awt.Dimension(145, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 1);
    jPanel1_3_2_2_1.add(DateRcvText, gridBagConstraints);

    JobTitleRcvLabel.setText("Job Title");
    JobTitleRcvLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_2_2_1.add(JobTitleRcvLabel, gridBagConstraints);

    DateRcvLabel.setText("Date");
    DateRcvLabel.setPreferredSize(new java.awt.Dimension(50, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
    jPanel1_3_2_2_1.add(DateRcvLabel, gridBagConstraints);

    jPanel1_3_2_2.add(jPanel1_3_2_2_1, java.awt.BorderLayout.WEST);

    jPanel1_3_2.add(jPanel1_3_2_2, java.awt.BorderLayout.CENTER);

    jPanel1_3.add(jPanel1_3_2, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel1_3, java.awt.BorderLayout.SOUTH);

    add(jPanel1, java.awt.BorderLayout.NORTH);

  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel AccountLabel;
  private javax.swing.JLabel AccountLabel2;
  private javax.swing.JTextField AccountText;
  private javax.swing.JTextField AccountText2;
  private javax.swing.JLabel AmountBaseCurrLabel;
  private javax.swing.JTextField AmountBaseCurrentText;
  private javax.swing.JLabel AmountLabel;
  private javax.swing.JTextField AmountText;
  private javax.swing.JLabel ChequeDueDateLabel;
  private javax.swing.JTextField ChequeDueDateText;
  private javax.swing.JLabel ChequeNoLabel;
  private javax.swing.JTextField ChequeNoText;
  private javax.swing.JLabel CurrencyLabel;
  private javax.swing.JTextField CurrencyText;
  private javax.swing.JLabel DateAppLabel;
  private javax.swing.JTextField DateAppText;
  private javax.swing.JLabel DateOriLabel;
  private javax.swing.JTextField DateOriText;
  private javax.swing.JLabel DateRcvLabel;
  private javax.swing.JTextField DateRcvText;
  private javax.swing.JLabel DescriptionLabel;
  private javax.swing.JLabel EmployeeAppLabel;
  private javax.swing.JTextField EmployeeAppText;
  private javax.swing.JLabel EmployeeOriLabel;
  private javax.swing.JTextField EmployeeOriText;
  private javax.swing.JLabel EmployeeRcvLabel;
  private javax.swing.JTextField EmployeeRcvText;
  private javax.swing.JLabel EndingBalanceLabel;
  private javax.swing.JTextField EndingBalanceText;
  private javax.swing.JLabel ExchRateLabel;
  private javax.swing.JTextField ExchRateText;
  private javax.swing.JLabel InitialLoanLabel;
  private javax.swing.JTextField InitialLoanText;
  private javax.swing.JLabel JobTitleAppLabel;
  private javax.swing.JTextField JobTitleAppText;
  private javax.swing.JLabel JobTitleOriLabel;
  private javax.swing.JTextField JobTitleOriText;
  private javax.swing.JLabel JobTitleRcvLabel;
  private javax.swing.JTextField JobTitleRcvText;
  private javax.swing.JLabel PayToLabel;
  private javax.swing.JTextField PayToText;
  private javax.swing.JComboBox PaymentSourceCombo;
  private javax.swing.JLabel PaymentSourceLabel;
  private javax.swing.JLabel RemarksLabel;
  private javax.swing.JLabel StatusLabel;
  private javax.swing.JTextField StatusText;
  private javax.swing.JLabel SubmittedDateLabel;
  private javax.swing.JTextField SubmittedDateText;
  private javax.swing.JLabel UnitCodeToLabel;
  private javax.swing.JTextField UnitCodeToText;
  private javax.swing.JLabel VoucherDateLabel;
  private javax.swing.JTextField VoucherDateText;
  private javax.swing.JLabel VoucherNoLabel;
  private javax.swing.JTextField VoucherNoText;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel1_1;
  private javax.swing.JPanel jPanel1_1_1;
  private javax.swing.JPanel jPanel1_2;
  private javax.swing.JPanel jPanel1_2_1;
  private javax.swing.JPanel jPanel1_2_1_1;
  private javax.swing.JPanel jPanel1_2_2;
  private javax.swing.JPanel jPanel1_2_2_1;
  private javax.swing.JPanel jPanel1_3;
  private javax.swing.JPanel jPanel1_3_1;
  private javax.swing.JPanel jPanel1_3_2;
  private javax.swing.JPanel jPanel1_3_2_1;
  private javax.swing.JPanel jPanel1_3_2_2;
  private javax.swing.JPanel jPanel1_3_2_2_1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JButton m_CancelBtn;
  private javax.swing.JButton m_DeleteBtn;
  private javax.swing.JButton m_EditBtn;
  private javax.swing.JButton m_NewBtn;
  private javax.swing.JButton m_SaveBtn;
  private javax.swing.JButton m_SubmitBtn;
  // End of variables declaration//GEN-END:variables

}